sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t awiegers/docker-react -f Dockerfile.dev .

script:
    - docker run awiegers/docker-react npm run test -- -- coverage