sudo: required
services:
    - docker

before_install:
    - docker build -t awiegers/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true awiegers/docker-react npm run test -- -- coverage