sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t awiegers/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true awiegers/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react3"
  env: "Dockerreact3-env"
  bucket_name: "elasticbeanstalk-us-east-2-307726917438"
  bucket_path: "docker-react3"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY